version: '3.3'

services:
  unit:
    build:
      context: .
      dockerfile: Dockerfile.test
    working_dir: /microservice
    command: bash -c "./gradlew test; chmod -R 777 testresult"
    volumes:
      - ./testresult:/microservice/testresult
